# Generated by Django 3.1.5 on 2021-01-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210113_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='active',
        ),
        migrations.AddField(
            model_name='bid',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_starting',
            field=models.BooleanField(default=False),
        ),
    ]
